DriverOnboarding/Controllers/VerificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using DriverOnboarding.Models;
using DriverOnboarding.Models.DBModels;
using DriverOnboarding.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DriverOnboarding.Controllers
{
    public class VerificationController : Controller
    {

        private gracelakemoovetestContext _context;

        public VerificationController(gracelakemoovetestContext context)
        {
            this._context = context;
        }

        // GET: Verification
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult ScheduledVerification()
        {
            ViewBag.PageTitle = "Drivers Scheduled For Verification";
            return View();
        }

        public IActionResult DriversScheduledVerificationData(IDataTablesRequest request)
        {
            try
            {
                var driversList = _context.Applications.Where(x => x.Scheduled == 1).ToList();

                var filteredData = String.IsNullOrWhiteSpace(request.Search.Value) ? driversList : driversList.Where(_item => _item.Surname.Contains(request.Search.Value) || _item.FirstName.Contains(request.Search.Value) || _item.Drn.Contains(request.Search.Value));

                var dataPage = filteredData.Skip(request.Start).Take(request.Length);

                var data = dataPage.Select(emList => new
                {
                    id = emList.Drn,
                    fullname = emList.FirstName + " " + emList.Surname + " " + emList.MiddleName,
                    address = emList.Address,
                    uberId = emList.UberId,
                    driverLicense = emList.DriverLicenseNumber,
                    contactDetails = "Email: " + emList.Email + " Tel: " + emList.Mobile,
                    applicationStatus = emList.ApplicationStatus,
                    dateCreated = Convert.ToDateTime(emList.CreatedDateTime).ToString("dd MMM yyyy"),
                }).ToList();

                dynamic response = DataTablesResponse.Create(request, driversList.Count(), filteredData.Count(), data);

                return new DataTablesJsonResult(response, true);
            }
            catch (Exception ex)
            {
                LogWorker logWorker = new LogWorker("VerificationController", "DriversScheduledVerificationData", ex.Message.ToString());
                throw ex;
            }

            //return new DataTablesJsonResult(response, true);
        }


        public ActionResult VerificationPendingApproval()
        {
            ViewBag.PageTitle = "Verification Pending For Approval";
            return View();
        }


        public IActionResult PendingVerificationForApprovalData(IDataTablesRequest request)
        {
            try
            {
                //var driversList = _context.Applications.Where(x => x.Scheduled == 1).ToList();

                var driverVerificationresult = (from driver in _context.Applications
                                               join vresult in _context.Verificationresult on driver.Drn equals vresult.RefNo
                                               join vresulta in _context.Verificationresultsapproval on driver.Drn equals vresulta.Drn
                                               where vresulta.FirstApproval == 0 && vresulta.SecondApproval == 0
                                               //into g from d in g.DefaultIfEmpty()
                                               select new
                                               {
                                                   driver.Id,
                                                   driver.Drn,
                                                   driver.FirstName,
                                                   driver.Surname,
                                                   driver.MiddleName,
                                                   driver.Mobile,
                                                   driver.Address,
                                                   driver.Email,
                                                   driver.ApplicationStatus,
                                                   vresult.Note,
                                                   vresult.VerificationItem,
                                                   vresult.CreatedDateTime,
                                                   vresult.Gps,
                                                   vresulta.FirstApproval,
                                                   vresulta.SecondApproval
                                               }).ToList();

                var distinct = driverVerificationresult.GroupBy(x => x.Drn, (key, group) => group.First());

                var filteredData = String.IsNullOrWhiteSpace(request.Search.Value) ? distinct : distinct.Where(_item => _item.Surname.Contains(request.Search.Value) || _item.FirstName.Contains(request.Search.Value) || _item.Drn.Contains(request.Search.Value));

                var dataPage = filteredData.Skip(request.Start).Take(request.Length);

                var data = dataPage.Select(emList => new
                {
                    id = emList.Id,
                    drn = emList.Drn,
                    fullname = emList.FirstName + " " + emList.Surname + " " + emList.MiddleName,
                    address = emList.Address,
                    //driverLicense = emList.DriverLicenseNumber,
                    contactDetails = "Email: " + emList.Email + " Tel: " + emList.Mobile,
                    applicationStatus = emList.ApplicationStatus,
                    verificationItem = emList.VerificationItem,
                    dateCreated = Convert.ToDateTime(emList.CreatedDateTime).ToString("dd MMM yyyy"),
                }).ToList();

                dynamic response = DataTablesResponse.Create(request, driverVerificationresult.Count(), filteredData.Count(), data);

                return new DataTablesJsonResult(response, true);
            }
            catch (Exception ex)
            {
                LogWorker logWorker = new LogWorker("VerificationController", "PendingVerificationForApprovalData", ex.Message.ToString());
                throw ex;
            }

            //return new DataTablesJsonResult(response, true);
        }


        // GET: Verification/Details/5
        public ActionResult VerificationDetails(int id, string drn)
        {
            try
            {
                if (id == 0)
                {
                    TempData["ErrorMsg"] = "Invalid Driver ID";
                    return RedirectToAction("index", "Drivers");
                }

                //ulong driverId = Convert.ToUInt64(id);

                ViewBag.PageTitle = "Driver Verification Details";
                ViewBag.DriverID = id;

                var driverDetails = (from d in _context.Applications
                                     join g in _context.Guarantordetails on d.Drn equals g.Drn into dg
                                     from g in dg.DefaultIfEmpty()
                                     join p in _context.Applicationpassports on d.Drn equals p.RefNo into dp
                                     from p in dp.DefaultIfEmpty()
                                     join dd in _context.Driverdocuments on d.Drn equals dd.Drn into ddd
                                     from dd in ddd.DefaultIfEmpty()
                                     join gd in _context.Guarantordocuments on d.Drn equals gd.Drn into dgd
                                     from gd in ddd.DefaultIfEmpty()
                                     where d.Drn == drn
                                     select new
                                     {
                                         Driver = d,
                                         Guarantor = g,
                                         DriverPassport = p,
                                         Driverdocuments = dd,
                                         Guarantordocuments = gd,
                                     }).ToList();

                var schedules = (from es in _context.Examinationschedules
                                 join e in _context.Examinations on Convert.ToUInt64(es.ExaminationId) equals e.Id
                                 where es.RefNo == drn
                                 //&& (es.Status == "Finished" || es.Status == "TimeElapsed")
                                 select new { es.RefNo, e.Subject, es.Score, es.PercentageScore, es.ModifiedDateTime }).ToList();

                var driverDocuments = (from dds in _context.Driverdocumenttypes
                                       join dd in _context.Driverdocuments
                                       on dds.DriverDocumentType equals dd.DocumentType
                                       where dd.Drn == drn
                                       select dd).ToList();

                var bankAccs = (from b in _context.Bankdetails
                                join dd in _context.Verifiedbankaccounts on b.AccountNumber equals dd.AccountNumber
                                where b.Drn == drn
                                select new BankDetailVerificationRes { sAccountName = b.AccountName, sAccountNumber = b.AccountNumber, dAccountName = dd.AccountName, dAccountNumber = dd.AccountNumber }).ToList();

                var bvnVerified = (from b in _context.Verifiedbvns
                                   join dd in _context.Applications on b.Bvn equals dd.Bvn
                                   where dd.Drn == drn
                                   select b).ToList();

                var subjects = _context.Verificationresultsapproval.Select(x => x.VerificationItem).ToList();

                var testOnboarding = (from e in _context.Examinationschedules

DriverOnboarding/Views/Verification/ScheduledVerification.cshtml
@{
    ViewData["Title"] = "ScheduledVerification";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Drivers</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Fullname</th>
                    <th>Address</th>
                    <th>UberId</th>
                    <th>Driver License</th>
                    <th>Contact Details</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

<script>
    $(document).ready(function() {
        $('#example1').dataTable( {
            "processing": true,
            "serverSide": true,
            "paging": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
            "datatype": "json",
            "ajax": {
                "url": "@Url.Action("DriversScheduledVerificationData", "Verification")",
                "type": "GET"
            },
            "columns": [
                { "data": "id" },
                { "data": "fullname" },
                { "data": "address" },
                { "data": "uberId" },
                { "data": "driverLicense" },
                { "data": "contactDetails" },
                { "data": "applicationStatus" },
                {}
            ],
            columnDefs: [
            {
                "searchable": false,
                "orderable": false,
                "targets": -1
            },{
                "data": null,
                "defaultContent": "",
                "targets": -1
            },
            { targets : [7],
                mRender: function (data, type, row, meta) {
                    var url = '@Url.Action("Details", "Drivers" )' + "/" + row.id;
                    return '<a href="' + url + '" class="btn btn-info viewdetails" data-container="body" data-toggle="m-tooltip" data-placement="top" data-original-title="View Details" title="View Details"><i class="fa fa-info-circle"></i></a>';
                    //if (row.StatusID == "3") {
                    //    //var userId = row.USER_NAME;
                    //    return '<a href="' + url + '" class="btn btn-info viewdetails" data-container="body" data-toggle="m-tooltip" data-placement="top" data-original-title="View Details" title="View Details"><i class="fa fa-info-circle"></i></a>';
                    //} else {
                    //    return '<a href="#" class="btn btn-danger statusModel" id="updateStatusbtn" data-projectid="' + row.id + '" data-projectdesc="' + row.ProjectName + '" data-projectstatus="' + row.StatusID + '"  data-container="body" data-placement="top" data-original-title="Update Status" title="Update Status" data-toggle="modal" data-target="#updateStatusModal"> <i class="fa fa-edit"></i></a> '+
                    //            '<a href="' + url + '" class="btn btn-info viewdetails" data-container="body" data-toggle="m-tooltip" data-placement="top" data-original-title="View Details" title="View Details"><i class="fa fa-info-circle"></i></a>';
                    //}
                }
            }
        ],
            "lengthMenu": [[50, 100, 150, 200], [50, 100, 150, 200]],
        });
    });
</script>

DriverOnboarding/Views/Verification/VerificationPendingApproval.cshtml
@{
    ViewData["Title"] = "VerificationPendingApproval";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Drivers</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Fullname</th>
                    <th>Address</th>
                    <th>Verification Item</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

<script>
    $(document).ready(function() {
        $('#example1').dataTable( {
            "processing": true,
            "serverSide": true,
            "paging": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
            "datatype": "json",
            "ajax": {
                "url": "@Url.Action("PendingVerificationForApprovalData", "Verification")",
                "type": "GET"
            },
            "columns": [
                { "data": "id" },
                { "data": "fullname" },
                { "data": "address" },
                { "data": "verificationItem" },
                { "data": "applicationStatus" },
                {}
            ],
            columnDefs: [
            {
                "searchable": false,
                "orderable": false,
                "targets": -1
            },{
                "data": null,
                "defaultContent": "",
                "targets": -1
            },
            { targets : [5],
                mRender: function (data, type, row, meta) {
                    var url = '@Url.Action("VerificationDetails", "Verification" )' + "/" + row.id+ "?drn=" + row.drn;
                    return '<a href="' + url + '" class="btn btn-info viewdetails" data-container="body" data-toggle="m-tooltip" data-placement="top" data-original-title="View Details" title="View Details"><i class="fa fa-info-circle"></i></a>';
                    //if (row.StatusID == "3") {
                    //    //var userId = row.USER_NAME;
                    //    return '<a href="' + url + '" class="btn btn-info viewdetails" data-container="body" data-toggle="m-tooltip" data-placement="top" data-original-title="View Details" title="View Details"><i class="fa fa-info-circle"></i></a>';
                    //} else {
                    //    return '<a href="#" class="btn btn-danger statusModel" id="updateStatusbtn" data-projectid="' + row.id + '" data-projectdesc="' + row.ProjectName + '" data-projectstatus="' + row.StatusID + '"  data-container="body" data-placement="top" data-original-title="Update Status" title="Update Status" data-toggle="modal" data-target="#updateStatusModal"> <i class="fa fa-edit"></i></a> '+
                    //            '<a href="' + url + '" class="btn btn-info viewdetails" data-container="body" data-toggle="m-tooltip" data-placement="top" data-original-title="View Details" title="View Details"><i class="fa fa-info-circle"></i></a>';
                    //}
                }
            }
        ],
            "lengthMenu": [[50, 100, 150, 200], [50, 100, 150, 200]],
        });
    });
</script>