DriverOnboarding/Models/DBModels/AppUsers.cs
using System;
using System.Collections.Generic;

namespace DriverOnboarding.Models.DBModels
{
    public partial class AppUsers
    {
        public ulong Id { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Supervisor { get; set; }
        public sbyte ForceChangePassword { get; set; }
        public string Password { get; set; }
        public sbyte CanChangeCompany { get; set; }
        public sbyte Enabled { get; set; }
        public string DefaultCompany { get; set; }
        public string PreviousCompany { get; set; }
        public int LoginFailCount { get; set; }
        public string Branch { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedDateTime { get; set; }
        public string Company { get; set; }
        public long RecordVersion { get; set; }
        public long Deleted { get; set; }
    }
}

DriverOnboarding/Models/DBModels/Countries.cs
using System;
using System.Collections.Generic;

namespace DriverOnboarding.Models.DBModels
{
    public partial class Countries
    {
        public ulong Id { get; set; }
        public string CountryId { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string Branch { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedDateTime { get; set; }
        public string Company { get; set; }
        public long RecordVersion { get; set; }
        public long Deleted { get; set; }
    }
}

DriverOnboarding/Models/DBModels/States.cs
using System;
using System.Collections.Generic;

namespace DriverOnboarding.Models.DBModels
{
    public partial class States
    {
        public ulong Id { get; set; }
        public string StateId { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedDateTime { get; set; }
        public string Company { get; set; }
        public long RecordVersion { get; set; }
        public long Deleted { get; set; }
    }
}

DriverOnboarding/Models/DispatchSetup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DriverOnboarding.Models
{
    public class DispatchSetup
    {
        public int id { get; set; }
        public string schedulemode { get; set; }
        public int maxdispacth { get; set; }
    }
}

DriverOnboarding/Models/DriverDocumentSetup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DriverOnboarding.Models
{
    public class DriverDocumentSetup
    {
        public int id { get; set; }
        public string docName { get; set; }
        public string docType { get; set; }
        public string docStatus { get; set; }
    }
}

DriverOnboarding/Controllers/UtilitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DriverOnboarding.Models.DBModels;
using DriverOnboarding.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace DriverOnboarding.Controllers
{
    public class UtilitiesController : Controller
    {

        IConfiguration _iconfiguration;
        private gracelakemoovetestContext _context;

        public UtilitiesController(IConfiguration iconfiguration, gracelakemoovetestContext context)
        {
            _iconfiguration = iconfiguration;
            this._context = context;
        }


        public JsonResult GetBanks()
        {
            try
            {
                var bankList = _context.Bank.Select(st => new {
                    id = st.Id,
                    name = st.Name
                }).ToList();
                return Json(new { data = bankList });
            }
            catch (Exception ex)
            {
                //LogError logerror = new LogError();
                LogWorker logWorker = new LogWorker("UtilitiesController", "GetBanks", ex.Message.ToString());
                return Json(new { data = "Error has occured" });
            }
        }

        public JsonResult GetCountries()
        {
            try
            {
                var countryList = _context.Countries.Select(st => new {
                    id = st.Id,
                    name = st.Name
                }).ToList();
                return Json(new { data = countryList });
            }
            catch (Exception ex)
            {
                //LogError logerror = new LogError();
                LogWorker logWorker = new LogWorker("UtilitiesController", "GetCountries", ex.Message.ToString());
                return Json(new { data = "Error has occured" });
            }

        }


        public JsonResult GetStates()
        {
            try
            {
                var stateList = _context.States.Select(st => new {
                    id = st.Id,
                    name = st.Name
                }).ToList();
                return Json(new { data = stateList });
            }
            catch (Exception ex)
            {
                //LogError logerror = new LogError();
                LogWorker logWorker = new LogWorker("UtilitiesController", "GetStates", ex.Message.ToString());
                return Json(new { data = "Error has occured" });
            }
        }


        public JsonResult GetUsers()
        {
            try
            {
                var stateList = _context.AppUsers.Select(st => new {
                    id = st.Id,
                    name = st.Name
                }).ToList();
                return Json(new { data = stateList });
            }
            catch (Exception ex)
            {
                //LogError logerror = new LogError();
                LogWorker logWorker = new LogWorker("UtilitiesController", "GetStates", ex.Message.ToString());
                return Json(new { data = "Error has occured" });
            }
        }


        public JsonResult GetLGAs()
        {
            try
            {
                var stateList = _context.Localgovernments.Select(st => new {
                    id = st.Id,
                    name = st.Name
                }).ToList();
                return Json(new { data = stateList });
            }
            catch (Exception ex)
            {
                //LogError logerror = new LogError();
                LogWorker logWorker = new LogWorker("UtilitiesController", "GetLGAs", ex.Message.ToString());
                return Json(new { data = "Error has occured" });
            }
        }


        public JsonResult GetStateLGAs(string stateId)
        {
            try
            {
                var stateList = _context.Localgovernments.Where(x => x.StateId == stateId).Select(st => new {
                    id = st.Id,
                    name = st.Name
                }).ToList();
                return Json(new { data = stateList });
            }
            catch (Exception ex)
            {
                //LogError logerror = new LogError();
                LogWorker logWorker = new LogWorker("UtilitiesController", "GetStateLGAs", ex.Message.ToString());
                return Json(new { data = "Error has occured" });
            }
        }


    }
}

DriverOnboarding/Views/Admin/AppUsers.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Users</h3>
        @*<div class="box-tools pull-right">
                <a href="@Url.Action("CreateUsers", "Admin")" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> New Vendor</a>
            </div>*@
        <div class="card-tools">
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-default">
                New User
            </button>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @if (TempData["ErrorMsg"] != null)
        {
            <alert class="alert alert-danger">@TempData["ErrorMsg"]</alert>
        }
        @if (TempData["SuccessMsg"] != null)
        {
            <alert class="alert alert-success">@TempData["SuccessMsg"]</alert>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Supervisor</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">New User Form</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="Admin" asp-action="CreateUser" method="post">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Username</label>
                            <input type="text" class="form-control" name="username" id="username" placeholder="Enter Staff Username" required>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Supervisor</label>
                            <select class="form-control" name="supervisor" id="supervisor" required>
                                <option>Select Supervisor</option>
                            </select>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<script>
    $(document).ready(function() {
        $('#example1').dataTable( {
            "processing": true,
            "serverSide": true,
            "paging": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
            "datatype": "json",
            "ajax": {
                "url": "@Url.Action("GetAppUsers", "Admin")",
                "type": "GET"
            },
            "columns": [
                { "data": "id" },
                { "data": "fullanme" },
                { "data": "supervisor" },
                { "data": "enabled" },
                {}
            ],
            columnDefs: [
            {
                "searchable": false,
                "orderable": false,
                "targets": -1
            },{
                "data": null,
                "defaultContent": "",
                "targets": -1
            },
            { targets : [3],
                mRender: function (data, type, row, meta) {
                    if (row.enabled == "1") {
                        return "Active";
                    } else {
                        return "Deactivated"
                    }
                }
            },
            { targets : [4],
                mRender: function (data, type, row, meta) {
                    return '<button class="btn btn-success updateBtn" id="activeBtn" data-pid="'+row.id+'" data-statusid="1">Activate</button> ' +
                            '<button class="btn btn-danger updateBtn" id="disableBtn" data-pid="'+row.id+'" data-statusid="0">Deactivate</button>'
                }
            }
            ],
            "lengthMenu": [[50, 100, 150, 200], [50, 100, 150, 200]],
        });
    });

    $(document).on('click', '.updateBtn', function () {
        var pid = $(this).data('pid');
        var statusid = $(this).data('statusid');
        swal({
            title: "Are you sure?",
            //text: "Once deleted, you will not be able to recover this imaginary file!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then((updateStatus) => {
            if (updateStatus) {
                $.ajax({
                    url: '@Url.Action("UpdateUserStatus", "Admin")',
                    data: {
                        id: pid,
                        statusId: statusid,
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.status == "00") {
                            $('#example1').DataTable().ajax.reload();
                            swal("User status updated!");
                        }
                    }
                });
            }
        });
    });

    $.ajax({
            type: "GET",
            url: "@Url.Action("GetUsers", "Utilities")",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                $.each(data, function (index, item) {
                    requestData = item;
                    jQuery.grep(item, function(stateList, i) {
                        $('#supervisor').append($('<option>', {
                            value: stateList.name,
                            text: stateList.name
                        }));
                    });
                });
            }
        });
</script>

DriverOnboarding/Views/Admin/Countries.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Countries</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @if (TempData["ErrorMsg"] != null)
        {
            <alert class="alert alert-danger">@TempData["ErrorMsg"]</alert>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

<script>
    $(document).ready(function() {
        $('#example1').dataTable( {
            "processing": true,
            "serverSide": true,
            "paging": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
            "datatype": "json",
            "ajax": {
                "url": "@Url.Action("GetCountries", "Admin")",
                "type": "GET"
            },
            "columns": [
                { "data": "id" },
                { "data": "countryName" },
            ],
           "lengthMenu": [[50, 100, 150, 200], [50, 100, 150, 200]],
        });
    });
</script>

DriverOnboarding/Views/Admin/DispatchSetup.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Dispatch</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @if (TempData["ErrorMsg"] != null)
        {
        <alert class="alert alert-danger">@TempData["ErrorMsg"]</alert>
        }
        @if (TempData["SuccessMsg"] != null)
        {
            <alert class="alert alert-success">@TempData["SuccessMsg"]</alert>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Dispatch Schedule Mode</th>
                    <th>Max Schedule Per Dispatch</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

<div class="modal fade" id="modal-default">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Dispatch Schedule</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="Admin" asp-action="UpdateDispatchSetup" method="post">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Schedule Mode</label>
                            <input type="hidden" class="form-control paramsId" name="id" id="paramsId">
                            <input type="text" class="form-control docName" name="schedulemode" id="schedulemode" placeholder="Enter Scheme">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Max Dispacth</label>
                            <input type="text" class="form-control maxdispacth" name="maxdispacth" id="maxdispacth" placeholder="Enter Scheme">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<script>
    $(document).ready(function() {
        $('#example1').dataTable( {
            "processing": true,
            "serverSide": true,
            "paging": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
            "datatype": "json",
            "ajax": {
                "url": "@Url.Action("GetDispatchSetup", "Admin")",
                "type": "GET"
            },
            "columns": [
                { "data": "id" },
                { "data": "scheduleMode" },
                { "data": "maxDispacth" },
                {}
            ],
            "columnDefs": [
            {
                "searchable": false,
                "orderable": false,
                "targets": -1
            },{
                "data": null,
                "defaultContent": "",
                "targets": -1
            },
            { targets : [3],
                mRender: function (data, type, row, meta) {
                    return '<button class="btn btn-danger updateBtn" id="activeBtn" data-pid="' + row.id + '" data-schedulemode="' + row.scheduleMode + '" data-maxdispacth="' + row.maxDispacth + '" data-toggle="modal" data-target="#modal-default">Edit</button>';
                }
            }
            ],
           "lengthMenu": [[50, 100, 150, 200], [50, 100, 150, 200]],
        });
    });

    $(document).on('click', '.updateBtn', function () {
        var pid = $(this).data('pid');
        var schedulemode = $(this).data('schedulemode');
        var maxdispacth = $(this).data('maxdispacth');

        $("#paramsId").val(pid);
        $("#schedulemode").val(schedulemode);
        $("#maxdispacth").val(maxdispacth);
    });
</script>

DriverOnboarding/Views/Admin/DriverApprovalSetup.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Setup For Approving Drivers </h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @if (TempData["ErrorMsg"] != null)
        {
            <alert class="alert alert-danger">@TempData["ErrorMsg"]</alert>
        }
        @if (TempData["SuccessMsg"] != null)
        {
            <alert class="alert alert-success">@TempData["SuccessMsg"]</alert>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Driver Scheme</th>
                    <th>Guarantor Optional For Verfication</th>
                    <th>Guarantor Optional For Approval Submission</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<div class="modal fade" id="modal-default">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Setup</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="Admin" asp-action="UpdateDriverApprovalSetup" method="post">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Driver Scheme</label>
                            <input type="hidden" class="form-control paramsId" name="id" id="paramsId">
                            <input type="text" class="form-control" name="driverscheme" id="driverscheme" placeholder="Enter Scheme">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Guarantor Optional For Verfication</label>
                            <select class="form-control" name="guarantorOptionalForVerfication" id="guarantorOptionalForVerfication" required>
                                <option value="">Select Option</option>
                                <option value="1">True</option>
                                <option value="0">False</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Guarantor Optional For Approval Submission</label>
                            <select class="form-control" name="guarantorOptionalForApprovalSubmission" id="guarantorOptionalForApprovalSubmission" required>
                                <option value="">Select Option</option>
                                <option value="1">True</option>
                                <option value="0">False</option>
                            </select>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script>
    $(document).ready(function() {
        $('#example1').dataTable( {
            "processing": true,
            "serverSide": true,
            "paging": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
            "datatype": "json",
            "ajax": {
                "url": "@Url.Action("GetDriverApprovalSetup", "Admin")",
                "type": "GET"
            },
            "columns": [
                { "data": "id" },
                { "data": "driverscheme" },
                { "data": "guarantorOptionalForVerfication" },
                { "data": "guarantorOptionalForApprovalSubmission" },
                {}
            ],
            columnDefs: [
                {
                    "searchable": false,
                    "orderable": false,
                    "targets": -1
                },{
                    "data": null,
                    "defaultContent": "",
                    "targets": -1
                },
                { targets : [2],
                    mRender: function (data, type, row, meta) {
                        if (row.guarantorOptionalForVerfication == "1") {
                            return "True";
                        } else {
                            return "False"
                        }
                    }
                },
                { targets : [3],
                    mRender: function (data, type, row, meta) {
                        if (row.guarantorOptionalForApprovalSubmission == "1") {
                            return "True";
                        } else {
                            return "False"
                        }
                    }
                },
                { targets : [4],
                    mRender: function (data, type, row, meta) {
                        return '<button class="btn btn-danger updateBtn" id="updateBtn" data-pid="'+row.id+'" data-driverscheme="'+row.driverscheme+'" data-statusid="1" data-toggle="modal" data-target="#modal-default">Edit</button>'
                    }
                }
            ],
            "lengthMenu": [[50, 100, 150, 200], [50, 100, 150, 200]],
        });
    });

    $(document).on('click', '.updateBtn', function (){
        var pid = $(this).data('pid');
        var driverscheme = $(this).data('driverscheme');
        $("#paramsId").val(pid);
        $("#driverscheme").val(driverscheme);
    })
</script>

DriverOnboarding/Views/Admin/DriverDocumentSetup.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Driver Doc.</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        @if (TempData["ErrorMsg"] != null)
        {
            <alert class="alert alert-danger">@TempData["ErrorMsg"]</alert>
        }
        @if (TempData["SuccessMsg"] != null)
        {
            <alert class="alert alert-success">@TempData["SuccessMsg"]</alert>
        }
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Document Name</th>
                    <th>Document Type</th>
                    <th>Mandatory</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<div class="modal fade" id="modal-default">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Document</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-controller="Admin" asp-action="UpdateDriverDocumentSetup" method="post">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Document Name</label>
                            <input type="hidden" class="form-control paramsId" name="id" id="paramsId">
                            <input type="text" class="form-control docName" name="docName" id="docName" placeholder="Enter Scheme">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Document Type</label>
                            <input type="text" class="form-control docType" name="docType" id="docType" placeholder="Enter Scheme">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Required Statues</label>
                            <select class="form-control docStatus" name="docStatus" id="docStatus" required>
                                <option value="">Select Option</option>
                                <option value="Mandatory">Mandatory</option>
                                <option value="Optional">Optional</option>
                            </select>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script>
    $(document).ready(function() {
        $('#example1').dataTable( {
            "processing": true,
            "serverSide": true,
            "paging": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
            "datatype": "json",
            "ajax": {
                "url": "@Url.Action("GetDriverDocumentSetup", "Admin")",
                "type": "GET"
            },
            "columns": [
                { "data": "id" },
                { "data": "docName" },
                { "data": "docType" },
                { "data": "docStatus" },
                {}
            ],
            columnDefs: [
            {
                "searchable": false,
                "orderable": false,
                "targets": -1
            },{
                "data": null,
                "defaultContent": "",
                "targets": -1
            },
            { targets : [4],
                mRender: function (data, type, row, meta) {
                    return '<button class="btn btn-danger updateBtn" id="activeBtn" data-pid="' + row.id + '" data-doctype="' + row.docType + '" data-docname="' + row.docName + '"data-statusid="1" data-toggle="modal" data-target="#modal-default">Edit</button>';
                }
            }
            ],
            "lengthMenu": [[50, 100, 150, 200], [50, 100, 150, 200]],
        });
    });

    $(document).on('click', '.updateBtn', function () {
        var pid = $(this).data('pid');
        var docType = $(this).data('doctype');
        var docName = $(this).data('docname');

        $("#paramsId").val(pid);
        $("#docName").val(docName);
        $("#docType").val(docType);
    });
</script>